export const ROLES = {
  COMMOM: "",
  USER: "ROLE_USER",
  ADM: "ROLE_ADM",
};

export const MAP_PATH_ROLES = {
  TAREFAS: {
    GET_ALL: [ROLES.USER, ROLES.ADM],
    GET_ID: [ROLES.USER, ROLES.ADM],
    POST: [ROLES.USER, ROLES.ADM],
    PUT: [ROLES.USER, ROLES.ADM],
    DELETE_ID: [ROLES.USER, ROLES.ADM],
  },
  USUARIOS: {
    GET_ALL: [ROLES.ADM],
    GET_ID: [ROLES.USER, ROLES.ADM],
    POST: [ROLES.COMMOM, ROLES.USER, ROLES.ADM],
    PUT: [ROLES.USER, ROLES.ADM],
    DELETE_ID: [ROLES.ADM],
  },
};
